import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import 'fake-indexeddb/auto';
import {ReviewStore,SaveConflict} from '../js/storage.js';
import {createReview,makeBundle,validateBundle} from '../js/model-v2.js';
const m=JSON.parse(await fs.readFile(new URL('../data/manifest.json',import.meta.url),'utf8'));
const cases=new Map(await Promise.all(m.photos.map(async p=>[p.id,JSON.parse(await fs.readFile(new URL('../'+p.data_file,import.meta.url),'utf8'))])));
let serial=0;
async function database(label){return new ReviewStore(`test-${label}-${++serial}`).open();}
function record(expert=m.expert_ids[0],id=m.assignments[expert][0]){const r=createReview(cases.get(id),expert,m);r.hazard_accuracy=r.law_appropriateness='appropriate';r.case_appropriateness='insufficient';r.completeness='no_misses';return r;}
test('transaction save, reload and submitted-edit history preserve notes and revision',async()=>{const db=await database('history');const r=record();r.status='submitted';r.submitted_at=new Date().toISOString();r.note='保留意見';const saved=await db.save(r);assert.equal(saved.revision,1);const next=structuredClone(saved);next.status='draft';next.note='修訂意見';await db.save(next,1);const restored=new ReviewStore(db.name.replace('vlm330-expert-review-',''));await restored.open();assert.equal((await restored.get(m.id,r.expert_id,r.photo_id)).note,'修訂意見');const history=await db.request('history','readonly',s=>s.getAll());assert.equal(history.length,1);assert.equal(history[0].record.note,'保留意見');db.db.close();restored.db.close();});
test('two tabs cannot silently overwrite a newer revision',async()=>{const db=await database('conflict'),r=record(),saved=await db.save(r);await db.save({...saved,note:'分頁一'},1);await assert.rejects(()=>db.save({...saved,note:'分頁二'},1),SaveConflict);assert.equal((await db.get(m.id,r.expert_id,r.photo_id)).note,'分頁一');db.db.close();});
test('11 expert exports restore 330 unique assigned records and keep QA separate',async()=>{const source=await database('source'),destination=await database('destination'),qa=await database('qa');for(const expert of m.expert_ids){for(const id of m.assignments[expert]){const r=record(expert,id);r.status='submitted';r.submitted_at=new Date().toISOString();await source.save(r);}const b=makeBundle(m,expert,await source.all(m.id,expert));validateBundle(JSON.parse(JSON.stringify(b)),m);const result=await destination.importRecords(b.records);assert.equal(result.inserted,30);}assert.equal((await destination.all(m.id)).length,330);for(const expert of m.expert_ids)assert.equal((await destination.all(m.id,expert)).length,30);assert.equal((await qa.all(m.id)).length,0);source.db.close();destination.db.close();qa.db.close();});
test('newer import uses chronological timestamps, preserves old answers in history',async()=>{const db=await database('import'),r=record();r.updated_at='2026-10-09T08:00:00.000Z';await db.importRecords([r]);const newer={...r,note:'較新',updated_at:'2026-10-09T17:01:00+08:00'};assert.equal((await db.importRecords([newer])).skipped,1);assert.equal((await db.importRecords([newer],true)).replaced,1);assert.equal((await db.get(m.id,r.expert_id,r.photo_id)).note,'較新');assert.equal((await db.request('history','readonly',s=>s.getAll())).length,1);db.db.close();});
test('transaction failure does not partially import records or erase existing progress',async()=>{const db=await database('rollback'),a=record(),b=record('A02');const saved=await db.save({...a,note:'既有'});const original=db.db.transaction.bind(db.db);db.db.transaction=(...args)=>{const tx=original(...args);if(args[1]==='readwrite')queueMicrotask(()=>tx.abort());return tx;};await assert.rejects(()=>db.importRecords([b]));db.db.transaction=original;assert.equal((await db.all(m.id)).length,1);assert.deepEqual(await db.get(m.id,a.expert_id,a.photo_id),saved);db.db.close();});
test('legacy and simplified review databases stay separate without deleting old records',async()=>{const old=await database('legacy'),fresh=await database('simple');const r={...record(),schema_version:1,note:'舊資料'};await old.save(r);assert.equal((await fresh.all(m.id)).length,0);assert.equal((await old.all(m.id))[0].note,'舊資料');old.db.close();fresh.db.close();});
